import { Component } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { AgentsService } from '../../services/agents.service';
import { ActivatedRoute, Router } from '@angular/router';


@Component({
  selector: 'app-agent-details',
  standalone: true,
  imports: [FormsModule,ReactiveFormsModule],
  templateUrl: './agent-details.component.html',
  styleUrl: './agent-details.component.css'
})
export class AgentDetailsComponent {

  editMode = false;
  showEditButton = false;
  selectedAgent: any = {};
  originalAgent: any = {};
  agents: any[] = [];
  newAgent: any = {};
  id!:string;


  constructor(
    private route: ActivatedRoute,
    private agentService: AgentsService,
    private router: Router
  ) { }


  // method to get all complaints generated by this agent
  
  ngOnInit(): void {
    
    this.route.queryParams.subscribe(
      params => {
        this.editMode = params['edit_mode'] === 'true';
      }    
    );

    this.agentService.getAllAgents().subscribe(
      (resp) => {
        this.agents = resp;
        this.route.params.subscribe(
          
          params => {
            this.id = params['id'];
            this.selectedAgent = this.agents.find(
              agent => agent.id === parseInt(this.id)
            );
            this.originalAgent = { ...this.selectedAgent };
          }
        );
      }
    );
  }

  toggleEdit(): void {
    this.editMode = !this.editMode;
    this.showEditButton = !this.showEditButton;
    if (!this.editMode) {
      this.originalAgent = { ...this.selectedAgent };
      this.agentService.save(this.selectedAgent).subscribe(response => {
        this.selectedAgent = response;
        console.log('Form data saved:', this.selectedAgent);
        this.goToAgents()
      });
    }
  }
  onCancel(): void {
    this.editMode = false;
    this.selectedAgent = { ...this.originalAgent };
    this.showEditButton = !this.showEditButton;
    this.goToAgents();
  }

  goToAgents(): void {
    this.router.navigate(['/agent']);
  }
}
